language: cpp
compiler:
  - clang
before_install:
  - echo "yes" | sudo add-apt-repository ppa:eudoxos/llvm-3.1
  - sudo apt-get update
  - sudo apt-get install clang llvm-3.1
before_script:
  - cd src
script: make --keep-going
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - daniel+travis-ci@trvx.org
    on_success: change
    on_failure: always
